version: "3.8"

services:
  postgres_db:
    image: postgres:latest
    container_name: postgres_db
    restart: always
    env_file:
            - .env
    environment:
      - POSTGRES_PASSWORD=admin
    ports:
      - 5433:5432
    volumes:
      - pddata:/var/lib/postgresql/data
    
  redis:
    image: 'bitnami/redis:latest'
    container_name: cache
    restart: always
    ports:
      - 6379:6379
    environment:
      - ALLOW_EMPTY_PASSWORD=yes

  web:
    image: ecom-api
    build:
      context: .
    container_name: gingorm
    restart: always
    links:
      - postgres_db
      - redis
    depends_on:
      - redis
      - postgres_db
    ports:
      - 8080:8080
    volumes:
      - .:/app
    command: bash -c "go build -o gingorm . && ./gingorm"

  frontend:
    stdin_open: true
    build: 
      dockerfile: Dockerfile
      context: ../../react/bookstore
    ports:
      - 3000:3000

volumes:
  pddata:

