version: "3.8"
services:
  # redis:
  #   image: "redis:alpine"
  #   hostname: redis
  #   ports:
  #     - 6379:6379
  web:
    image: ecom-api
    build:
      context: .
    container_name: gingorm
    # depends_on:
    #   - redis
    ports:
      - 8080:8080
    volumes:
      - .:/app
    command: bash -c "go build -o gingorm . && ./gingorm"
