version: "3.8"
services:
  web:
    image: ecom-api
    build:
      context: .
    container_name: gingorm
    ports:
      - 8080:8080
    volumes:
      - ./:/app
    command: bash -c "go build -o gingorm . && ./gingorm"
